"""
PlatformIO extra script: generate forward declarations for k3ng_rotator_controller.ino.

Arduino IDE auto-generates function prototypes from .ino files before passing them to
the C++ compiler. The native PlatformIO build doesn't do this, so setup() and loop()
can't call functions defined later in the file. This script mimics the Arduino IDE step:
it runs ctags over the .ino, extracts all function signatures, and writes a header that
native_k3ng.cpp includes before #include-ing the .ino.
"""

Import("env")  # noqa: F821 — PlatformIO injects this
import subprocess, os, re

INO = os.path.join(env["PROJECT_SRC_DIR"], "k3ng_rotator_controller.ino")
OUT = os.path.join(env["PROJECT_SRC_DIR"], "rotator_native_declarations.h")

# ctags field format:
#   name\tfile\t/^src/;"\tf\ttyperef:typename:RETTYPE\tsignature:(PARAMS)
CTAGS_RE = re.compile(
    r'^(\S+)\t[^\t]+\t[^\t]+\tf\ttyperef:typename:(.+?)\tsignature:(\(.*\))\s*$'
)

def run():
    result = subprocess.run(
        [
            "ctags", "-f", "-",
            "--language-force=C++",
            "--c-kinds=f",
            "--fields=+S",
            INO,
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("gen_ino_declarations: ctags failed:", result.stderr)
        return

    decls = []
    seen = set()
    for line in result.stdout.splitlines():
        m = CTAGS_RE.match(line)
        if not m:
            continue
        name, rettype, params = m.group(1), m.group(2).strip(), m.group(3)
        if name in ("setup", "loop", "main"):
            continue
        if name in seen:
            continue
        seen.add(name)
        decls.append(f"{rettype} {name}{params};")

    header = (
        "// Auto-generated by extra_scripts/gen_ino_declarations.py — DO NOT EDIT\n"
        "// Provides C++ forward declarations for all functions in\n"
        "// k3ng_rotator_controller.ino (Arduino IDE generates these automatically).\n"
        "#pragma once\n"
        "#ifdef NATIVE_BUILD\n"
        "#include <cstdint>\n"
        "#include <ctime>\n"
        "#include \"Arduino.h\"\n"
        "\n"
    ) + "\n".join(decls) + "\n\n#endif // NATIVE_BUILD\n"

    with open(OUT, "w") as f:
        f.write(header)
    print(f"gen_ino_declarations: wrote {len(decls)} declarations to {OUT}")

run()
